version: "3.8"

services: 
  postgres:
    image: postgres:14.1-alpine
    # restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./data:/var/lib/postgresql/data


# https://geshan.com.np/blog/2021/12/docker-postgres/


  